data = {
    0 : {
        'PATH' : 'pic/plant/subflower/%d.png',
        'IMAGE_INDEX_MAX' : 19,
        'IMAGE_INDEX_CD' : 0.07,
        'SUMMON_CD' : 8,
        'POSITION_CD' : 0.05,
        'SIZE' : (128, 128),
        'HP' : 5,
        'ATT' : 0,
        'PRICE' : 20,
        'CAN_LOOT' : False,
    },
    1 : { 
        'PATH' : 'pic/plant/peashooter/%d.png',
        'IMAGE_INDEX_MAX' : 15,
        'IMAGE_INDEX_CD' : 0.15,
        'SUMMON_CD' : 3,
        'POSITION_CD' : 0.05,
        'SIZE' : (128, 128),
        'HP' : 6,
        'ATT' : 0,
        'PRICE' : 30,
        'CAN_LOOT' : False,
    },
    2 : {
        'PATH' : 'pic/other/sunlight/%d.png',
        'IMAGE_INDEX_MAX' : 30,
        'IMAGE_INDEX_CD' : 0.06,
        'SUMMON_CD' : -1,
        'POSITION_CD' : 0.05,
        'SIZE' : (80, 80),
        'HP' : 10000000,
        'ATT' : 0,
        'PRICE' : 5,
        'CAN_LOOT' : True,
    },
    3 : {
        'PATH' : 'pic/other/peabullet.png',
        'IMAGE_INDEX_MAX' : 0,
        'IMAGE_INDEX_CD' : 0.00,
        'SUMMON_CD' : -1,
        'POSITION_CD' : 0.01,
        'SIZE' : (32, 32),
        'HP' : 1,
        'ATT' : 1,
        'PRICE' : 0,
        'CAN_LOOT' : False,
    },
    4 : {
        'PATH' : 'pic/zombie/0/%d.png',
        'IMAGE_INDEX_MAX' : 15,
        'IMAGE_INDEX_CD' : 0.2,
        'SUMMON_CD' : -1,
        'POSITION_CD' : 0.15,
        'SIZE' : (101, 126),
        'HP' : 5,
        'ATT' : 1,
        'PRICE' : 0,
        'CAN_LOOT' : False,
    },
}
